### ISSUE TITLE
As a user, I want to have a nice product display so that I can easily browse through products.

### ISSUE THREAD

**Issue by Janainaacm** [Janainaacm/DigitalStock#11]
### TODO

- [x] Product page styling
- [x] Product details styling
- [x] Display available colors in product details
