### ISSUE TITLE
As a user, I want to be able to filter the products by search or category so that I can easily find what I'm looking for.

### ISSUE THREAD

**Issue by Janainaacm** [Janainaacm/DigitalStock#12]
### TODO

- [x] Filter product list by category
- [x] Filter product list by search
- [x] Display filtered list
- [ ] Display keyword
