### ISSUE TITLE
As a user, I want to be able to log in to my account and view my profile so that I can have my information and activity saved.

### ISSUE THREAD

**Issue by Janainaacm** [Janainaacm/DigitalStock#4]
### TODO
- [x] Log in authentication
- [x] Register authentication 
- [x] Log out function

**Profile page**
- [x] View and manipulate user information
- [x] View orders based on status
- [x] View wishlist
