### ISSUE TITLE
As a User, I want to see a list of items displayed as cards on the page, so I can easily view product details such as title, description and price

### ISSUE THREAD

**Issue by Janainaacm** [Janainaacm/DigitalStock#4]
##TODO

- [ ] Tailwind basics (Flexbox, Grid)
- [ ] Fetch (Client & Server components)
- [ ] TSX syntax with Card
