### ISSUE TITLE
As an Admin, I want to have a control panel so that I can manage all info from one place.

### ISSUE THREAD

**Issue by Janainaacm** [Janainaacm/DigitalStock#6]
### TODO

**Admin page**
_Products:_
- [x] Overview of products
- [x] Edit products information
- [x] Add product
- [x] Remove product

_Orders:_
- [x] Overview of orders
- [x] Edit order status

_Users:_
- [x] Overview of users
- [x] User profile view, including activity as orders, wishlist, info etc
