### ISSUE TITLE
As a User, I want to have a dynamic cart functionality so that I can take my time deciding what to buy.

### ISSUE THREAD

**Issue by Janainaacm** [Janainaacm/DigitalStock#7]
### TODO

- [x] Consistent cart connected to the user
- [x] Cart dropdown from Navbar
- [ ] A Cart page
- [ ] A checkout page to place order
