### ISSUE TITLE
As a user, I want to have a Navbar so that I can easily access important pages.

### ISSUE THREAD

**Issue by Janainaacm** [Janainaacm/DigitalStock#9]
### TODO

- [x] Navbar in header at all times
- [x] Wishlist icon
- [x] Cart icon
- [x] Profile page icon
- [x] Searchbar
- [x] Main pages as titles
